### ISSUE TITLE
unknown crash SIGSEGV (#0  0x0000003e51238df4 in g_hash_table_lookup_node (hash_return=<synthetic pointer>, key=0xfe10f0, hash_table=0x752d73616d656863) at ghash.c:368)

### ISSUE THREAD

**Issue by ignatenkobrain** [01org/dleyna-renderer#149]
```
(gdb) t a a bt full

Thread 3 (Thread 0x7f2863495700 (LWP 20308)):
#0  0x0000003e496f97dd in poll () at /lib64/libc.so.6
#1  0x0000003e51249ea4 in g_main_context_iterate (priority=2147483647, n_fds=3, fds=0x7f285c0010c0, timeout=-1, context=0xf9a440) at gmain.c:4029
        poll_func = 0x3e512592a0 <g_poll>
        max_priority = 2147483647
        timeout = -1
        some_ready = <optimized out>
        nfds = 3
        allocated_nfds = 3
        fds = 0x7f285c0010c0
#2  0x0000003e51249ea4 in g_main_context_iterate (context=0xf9a440, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3729
        max_priority = 2147483647
        timeout = -1
        some_ready = <optimized out>
        nfds = 3
        allocated_nfds = 3
        fds = 0x7f285c0010c0
#3  0x0000003e5124a232 in g_main_loop_run (loop=0xf9a3d0) at gmain.c:3928
        __FUNCTION__ = "g_main_loop_run"
#4  0x0000003e526e27a6 in gdbus_shared_thread_func (user_data=0xf9a410) at gdbusprivate.c:273
        data = 0xf9a410
#5  0x0000003e512709a5 in g_thread_proxy (data=0xf9c450) at gthread.c:764
        thread = 0xf9c450
#6  0x0000003e49e075fa in start_thread () at /lib64/libpthread.so.0
#7  0x0000003e49704e0d in clone () at /lib64/libc.so.6

Thread 2 (Thread 0x7f286128d700 (LWP 20312)):
#0  0x0000003e496ff499 in syscall () at /lib64/libc.so.6
#1  0x0000003e5128e637 in g_cond_wait_until (cond=cond@entry=0xfb6de8, mutex=mutex@entry=0xfb6de0, end_time=end_time@entry=15706236208) at gthread-posix.c:1437
        now = {tv_sec = 15691, tv_nsec = 236209811}
        span = {tv_sec = 14, tv_nsec = 999998189}
        sampled = 0
        res = <optimized out>
#2  0x0000003e5121ec39 in g_async_queue_pop_intern_unlocked (queue=queue@entry=0xfb6de0, wait=wait@entry=1, end_time=end_time@entry=15706236208) at gasyncqueue.c:422
        retval = <optimized out>
        __FUNCTION__ = "g_async_queue_pop_intern_unlocked"
#3  0x0000003e5121f25b in g_async_queue_timeout_pop (queue=0xfb6de0, timeout=timeout@entry=15000000) at gasyncqueue.c:543
        end_time = 15706236208
        retval = <optimized out>
#4  0x0000003e512713fc in g_thread_pool_thread_proxy () at gthreadpool.c:167
---Type <return> to continue, or q <return> to quit---
        pool = <optimized out>
        local_wakeup_thread_serial = <optimized out>
        last_wakeup_thread_serial = <optimized out>
        have_relayed_thread_marker = <optimized out>
        free_pool = <optimized out>
        task = 0x2
        pool = <optimized out>
#5  0x0000003e512713fc in g_thread_pool_thread_proxy (data=<optimized out>) at gthreadpool.c:364
        free_pool = <optimized out>
        task = 0x2
        pool = <optimized out>
#6  0x0000003e512709a5 in g_thread_proxy (data=0x7f285c003c50) at gthread.c:764
        thread = 0x7f285c003c50
#7  0x0000003e49e075fa in start_thread () at /lib64/libpthread.so.0
#8  0x0000003e49704e0d in clone () at /lib64/libc.so.6

Thread 1 (Thread 0x7f2863d33840 (LWP 20305)):
#0  0x0000003e51238df4 in g_hash_table_lookup (hash_return=<synthetic pointer>, key=0xfe10f0, hash_table=<error reading variable: Cannot access memory at address 0x752d73616d656893>0x752d73616d656863) at ghash.c:368
        node_hash = <optimized out>
        hash_value = <optimized out>
        have_tombstone = 0
        step = 0
        node_index = <optimized out>
        first_tombstone = 0
        node_hash = <optimized out>
        __FUNCTION__ = "g_hash_table_lookup"
#1  0x0000003e51238df4 in g_hash_table_lookup (hash_table=<error reading variable: Cannot access memory at address 0x752d73616d656893>0x752d73616d656863, key=key@entry=0xfe10f0) at ghash.c:1092
        node_hash = <optimized out>
        __FUNCTION__ = "g_hash_table_lookup"
#2  0x0000003e4c20faeb in prv_server_available_cb (cp=<optimized out>, proxy=0xfded90 [GUPnPDeviceProxy], user_data=0xfb8400) at upnp.c:174
        upnp = 0xfb8400
        udn = 0xfe10f0 "uuid:ec8aba15-a446-423b-92b3-ff87ca9a5554"
        device = <optimized out>
        ip_address = 0xfbbf20 "127.0.0.1"
        context = <optimized out>
        queue_id = <optimized out>
        i = <optimized out>
        priv_t = 0x7fffded101c0
#3  0x0000003e51e131ab in g_cclosure_marshal_VOID__OBJECTv (closure=0xfc7570, return_value=<optimized out>, instance=<optimized out>, args=<optimized out>, marshal_data=0x0, n_---Type <return> to continue, or q <return> to quit---
params=<optimized out>, param_types=0xfc6b80) at gmarshal.c:1312
        cc = 0xfc7570
        data1 = <optimized out>
        data2 = <optimized out>
        callback = <optimized out>
        arg0 = 0xfded90
        args_copy = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7fffded104b0, reg_save_area = 0x7fffded103f0}}
#4  0x0000003e51e10104 in _g_closure_invoke_va (closure=0xfe10f0, closure@entry=0xfc7570, return_value=0xfe10f0, return_value@entry=0x0, instance=0x1, 
    instance@entry=0xfa0960, args=0x1, args@entry=0x7fffded103d0, n_params=1277229712, param_types=0xfb9600) at gclosure.c:831
        marshal = 0xfbbf20
        marshal_data = 0x3e4c20fa90 <prv_server_available_cb>
        __FUNCTION__ = "_g_closure_invoke_va"
#5  0x0000003e51e2aaa0 in g_signal_emit_valist (instance=0xfa0960, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7fffded103d0) at gsignal.c:3218
        return_accu = 0x0
        accu = 
              {g_type = 0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        accumulator = 0x0
        emission = {next = 0x0, instance = 0xfa0960, ihint = {signal_id = 31, detail = 0, run_type = G_SIGNAL_RUN_FIRST}, state = EMISSION_RUN, chain_type = 16534608}
        signal_id = 31
        instance_type = 16534608
        emission_return = 
              {g_type = 0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        rtype = 4
        static_scope = 0
        fastpath_handler = <optimized out>
        closure = 0xfc7570
        run_type = <optimized out>
        l = <optimized out>
        fastpath = <optimized out>
        instance_and_params = <optimized out>
        signal_return_type = <optimized out>
        param_values = <optimized out>
        node = <optimized out>
        i = <optimized out>
        n_params = <optimized out>
        __FUNCTION__ = "g_signal_emit_valist"
#6  0x0000003e51e2b2ef in g_signal_emit (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at gsignal.c:3365
        var_args = {{gp_offset = 24, fp_offset = 48, overflow_arg_area = 0x7fffded104b0, reg_save_area = 0x7fffded103f0}}
#7  0x0000003e54e0fd87 in process_device_list (url_base=<optimized out>, description_url=<optimized out>, udn=<optimized out>, element=<optimized out>, doc=<optimized out>, con---Type <return> to continue, or q <return> to quit---
trol_point=<optimized out>) at gupnp-control-point.c:320
        proxy = 0xfded90 [GUPnPDeviceProxy]
        factory = 0xfded90 [GUPnPDeviceProxy]
        context = 0xfbbf20
        prop = 0xfded90 "\200\016\376"
#8  0x0000003e54e0fd87 in process_device_list (control_point=0xfe10f0, control_point@entry=0xfa0960 [GUPnPControlPoint], doc=0x1, 
    doc@entry=0xfaac40 [GUPnPXMLDoc], udn=0x1 <error: Cannot access memory at address 0x1>, 
    udn@entry=0xfd45b0 "uuid:ec8aba15-a446-423b-92b3-ff87ca9a5554", service_type=0x0, description_url=0xfb9600 "\002", 
    description_url@entry=0xfdaed0 "http://127.0.0.1:46961/ec8aba15-a446-423b-92b3-ff87ca9a5554.xml", url_base=0xfd9d40, element=<optimized out>) at gupnp-control-point.c:475
        prop = 0xfded90 "\200\016\376"
#9  0x0000003e54e0fe01 in description_loaded (control_point=0xfa0960 [GUPnPControlPoint], doc=0xfaac40 [GUPnPXMLDoc], udn=0xfd45b0 "uuid:ec8aba15-a446-423b-92b3-ff87ca9a5554", service_type=0x0, description_url=0xfdaed0 "http://127.0.0.1:46961/ec8aba15-a446-423b-92b3-ff87ca9a5554.xml") at gupnp-control-point.c:519
        element = 0xfe15d0
        url_base = 0xfd9d40
#10 0x0000003e54e100eb in got_description_url (session=<optimized out>, msg=<optimized out>, data=0x7f285c00e2c0) at gupnp-control-point.c:571
        xml_doc = <optimized out>
        doc = 0xfaac40 [GUPnPXMLDoc]
        session = <optimized out>
        data = 0x7f285c00e2c0
        msg = <optimized out>
        doc = <optimized out>
#11 0x0000003e65e7186a in soup_session_process_queue_item (session=0xfe10f0, item=0xfbf940, should_cleanup=0x1, loop=1) at soup-session.c:2001
#12 0x0000003e65e7217d in async_run_queue (session=0xfc2110 [SoupSessionAsync]) at soup-session.c:2040
        priv = 0xfc2000
        item = 0xfbf940
        msg = <optimized out>
        try_cleanup = <optimized out>
        should_cleanup = 0
#13 0x0000003e65e72264 in idle_run_queue (user_data=0xfc2000) at soup-session.c:2074
        priv = 0xfc2000
        source = 0xfe2710
#14 0x0000003e51249b6b in g_main_context_dispatch (context=0xf7dea0) at gmain.c:3064
        dispatch = 0x3e512466f0 <g_idle_dispatch>
        prev_source = 0x0
        was_in_call = 0
        user_data = 0xfc2000
        callback = 0x3e65e72210 <idle_run_queue>
        cb_funcs = 0x3e515378c0 <g_source_callback_funcs>
        cb_data = 0xfde5a0
        need_destroy = <optimized out>
        source = 0xfe2710
---Type <return> to continue, or q <return> to quit---
        current = 0xf97220
        i = 0
#15 0x0000003e51249b6b in g_main_context_dispatch (context=context@entry=0xf7dea0) at gmain.c:3663
#16 0x0000003e51249f08 in g_main_context_iterate (context=0xf7dea0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3734
        max_priority = 0
        timeout = 0
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = 15
        fds = 0xfd9280
#17 0x0000003e5124a232 in g_main_loop_run (loop=0xfb6b10) at gmain.c:3928
        __FUNCTION__ = "g_main_loop_run"
#18 0x0000003e4be03b8c in dleyna_main_loop_start (server=server@entry=0x400f90 "dleyna-renderer-service", control_point=<optimized out>, user_data=user_data@entry=0x0)
    at libdleyna/core/main-loop.c:155
        retval = 1
#19 0x0000000000400dd0 in main (argc=<optimized out>, argv=<optimized out>) at daemon.c:93
        mask = {__val = {16386, 0 <repeats 15 times>}}
        retval = 1
```

**Comment by debarshiray** [comment]
I believe that the necessary fixes for this have been merged into dleyna-renderer, dleyna-connector-dbus and gupnp.

**Comment by rsbells** [comment]
Patch - Pulls have been merged...
https://github.com/01org/dleyna-core/pull/48
https://github.com/01org/dleyna-core/pull/49
https://github.com/01org/dleyna-renderer/pull/160

**Comment by rsbells** [comment]
the last changes in GUPnP relating to dLeyna that I remember are
https://git.gnome.org/browse/gupnp/commit/?id=d2e0dc2a8fdb104950f01f153ff60eb663de7a88
https://git.gnome.org/browse/gupnp/commit/?id=ed009b4d497e748f43887e91f4f777c6cdb5e43d

And those were part of GUPnP 0.20.15 which should be available.
